version: '3'
services:
  react-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules # pour ne pas écraser node_modules avec ton host
    environment:
      - CHOKIDAR_USEPOLLING=true # pour que React détecte bien les modifs
